services:
  db:
    image: postgres:16-alpine
    container_name: auth-crud-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mpatel@2026
      POSTGRES_DB: test-auth-crud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test-auth-crud"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: dockerfile
    image: auth-crud-app:latest
    container_name: auth-crud-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "3000:3000"

volumes:
  postgres_data:
