name: CI Pipeline

on:
  push:
    branches: [feat/test-apis-database]
  pull_request:
    branches: [feat/test-apis-database]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-apis-database
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
      TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
      TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: test-apis-database/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Test Code
        run: npm run test

      - name: Build App
        run: npm run build

      - name: Build Docker Images
        run: docker build -t test-api .
